#lang racket

; Exercise 1.9.
; Each of the following two procedures defines a method for
; adding two positive integers in terms of the procedures add1,
; which increments its argument by 1, and sub1,
; which decrements its argument by 1.

(define (add-v1 a b)
  (if (= a 0)
      b
      (add1 (add-v1 (sub1 a) b))))

(define (add-v2 a b)
  (if (= a 0)
      b
      (add-v2 (sub1 a) (add1 b))))

; Using the substitution model, illustrate the process
; generated by each procedure in evaluating (+ 4 5).
; Are these processes iterative or recursive?

; Answer:

(displayln "add-v1")
(add-v1 4 5)
(add1 (add-v1 3 5))
(add1 (add1 (add-v1 2 5)))
(add1 (add1 (add1 (add-v1 1 5))))
(add1 (add1 (add1 (add1 (add-v1 0 5)))))
(add1 (add1 (add1 (add1 5))))
(add1 (add1 (add1 6)))
(add1 (add1 7))
(add1 8)
9

; We can see, this is a recursive process.

(displayln "add-v2")
(add-v2 4 5)
(add-v2 (sub1 4) (add1 5))
(add-v2 3 6)
(add-v2 2 7)
(add-v2 1 8)
(add-v2 0 9)
9

; We can see, this is an iterative process.