#lang racket

; Exercise 1.14.
; Draw the tree illustrating the process generated by the
; count-change procedure of section 1.2.2 in making change
; for 11 cents. What are the orders of growth of the space
; and number of steps used by this process as the amount to
; be changed increases?

; Answer:
; (cc 11 5)
;  (cc -39 5) => 0
;  (cc 11 4)
;    (cc -14 4) => 0
;    (cc 11 3)
;      (cc 1 3)
;        (cc -9 3) => 0
;        (cc 1 2)
;          (cc -4 2) => 0
;          (cc 1 1)
;            (cc 0 1) => 1
;            (cc 1 0) => 0
;      (cc 11 2)
;        (cc 6 2)
;          (cc 1 2)
;            (cc -4 2) => 0
;            (cc 1 1)
;              (cc 0 1) => 1
;              (cc 1 0) => 0
;          (cc 6 1)
;            (cc 5 1)
;              (cc 4 1)
;                (cc 3 1)
;                  (cc 2 1)
;                    (cc 1 1)
;                      (cc 0 1) => 1
;                      (cc 1 0) => 0
;                    (cc 2 0) => 0
;                  (cc 3 0) => 0
;                (cc 4 0) => 0
;              (cc 5 0) => 0
;            (cc 6 0) => 0
;        (cc 11 1)
;          (cc 10 1)
;            (cc 9 1)
;              (cc 8 1)
;                (cc 7 1)
;                  (cc 6 1)
;                    (cc 5 1)
;                      (cc 4 1)
;                        (cc 3 1)
;                          (cc 2 1)
;                            (cc 1 1)
;                              (cc 0 1) => 1
;                              (cc 1 0) => 0
;                            (cc 2 0) => 0
;                          (cc 3 0) => 0
;                        (cc 4 0) => 0
;                      (cc 5 0) => 0
;                    (cc 6 0) => 0
;                  (cc 7 0) => 0
;                (cc 8 0) => 0
;              (cc 9 0) => 0
;            (cc 10 0) => 0
;          (cc 11 0) => 0

; Think of the recursion as a set of nested loops, one for each coin type.

; To make change for amount nn with $k$ kinds of coins,
; we first decide how many of the largest coin (say value $d_k$) to use:
; we can use 0, 1, 2, ... up to about $n/d_k$ of them.
; That’s roughly $n$ possibilities (ignoring the constant division).

; For each choice of how many largest coins, the remaining amount is smaller,
; and we now need to make change for that remaining amount using only the remaining
; $k−1$ kinds of coins.

; That subproblem itself is another loop over the next largest coin,
; again with about $n$ possibilities (scaled by its denomination).

; So we have $k$ levels of loops, each iterating about $n$ times
; (the exact number is $n/d_i$, but all are proportional to $n$).
; The total number of combinations we explore is
; roughly the product of the loop sizes:
; $$
; \underbrace{n \times n \times \dots \times n}_{k\text{ times}} = n^k.
; $$

; Let's check:

(define (count-change amount)
  (define rec (make-hasheq))
  (cc amount 5 rec))

(define (cc amount kinds-of-coins rec)
  (cond [(= amount 0) '(1 1)]
        [(or (< amount 0) (= kinds-of-coins 0)) '(0 1)]
        [else
         (let ([input (list amount kinds-of-coins)])
           (if (hash-has-key? rec input)
               (hash-ref rec input)
               (match-let*
                   ([(list r1 c1)
                     (cc amount
                         (- kinds-of-coins 1) rec)]
                    [(list r2 c2)
                     (cc (- amount
                            (first-denomination kinds-of-coins))
                         kinds-of-coins rec)]
                    [result (list (+ r1 r2) (+ c1 c2 1))])
                    (hash-set! rec input result)
                    result)))]))

(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(require plot)

(define n-max 200)

(define results
  (for/list ([i (in-range (add1 n-max))])
    (match-let ([(list r c) (count-change i)])
      c)))

(define c-max (list-ref results n-max))
(define k-est (/ c-max (expt n-max 5)))
(define k (* k-est 0.9))

(define curve
  (for/list ([n (in-range (add1 n-max))])
    (vector n (* k (expt n 5)))))

(define data-line
  (lines (for/list ([n (in-naturals)] [c results])
           (vector n c))
         #:color 'blue
         #:label "Real Calculation"))
(define fit-line
  (lines curve
         #:color 'green
         #:style 'dot
         #:label "Analysis"))

(plot (list data-line fit-line)
      #:x-label "Target Money"
      #:y-label "Calculation Count")